import Header from "@/components/profile/Header";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";

export const metadata = {
  title: "Authentication App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <div>
            <Header />
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
